config/routes.rb
CupidParty2::Application.routes.draw do
  resources :messages

  resources :sweethearties

  resources :rates

  resources :users

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/rate.rb
class Rate < ActiveRecord::Base
end

app/models/sweethearty.rb
class Sweethearty < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :ok }
    end
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rates }
    end
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/new
  # GET /rates/new.json
  def new
    @rate = Rate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/1/edit
  def edit
    @rate = Rate.find(params[:id])
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(params[:rate])

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render json: @rate, status: :created, location: @rate }
      else
        format.html { render action: "new" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rates/1
  # PUT /rates/1.json
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sweethearties_controller.rb
class SweetheartiesController < ApplicationController
  # GET /sweethearties
  # GET /sweethearties.json
  def index
    @sweethearties = Sweethearty.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sweethearties }
    end
  end

  # GET /sweethearties/1
  # GET /sweethearties/1.json
  def show
    @sweethearty = Sweethearty.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sweethearty }
    end
  end

  # GET /sweethearties/new
  # GET /sweethearties/new.json
  def new
    @sweethearty = Sweethearty.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sweethearty }
    end
  end

  # GET /sweethearties/1/edit
  def edit
    @sweethearty = Sweethearty.find(params[:id])
  end

  # POST /sweethearties
  # POST /sweethearties.json
  def create
    @sweethearty = Sweethearty.new(params[:sweethearty])

    respond_to do |format|
      if @sweethearty.save
        format.html { redirect_to @sweethearty, notice: 'Sweethearty was successfully created.' }
        format.json { render json: @sweethearty, status: :created, location: @sweethearty }
      else
        format.html { render action: "new" }
        format.json { render json: @sweethearty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sweethearties/1
  # PUT /sweethearties/1.json
  def update
    @sweethearty = Sweethearty.find(params[:id])

    respond_to do |format|
      if @sweethearty.update_attributes(params[:sweethearty])
        format.html { redirect_to @sweethearty, notice: 'Sweethearty was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sweethearty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sweethearties/1
  # DELETE /sweethearties/1.json
  def destroy
    @sweethearty = Sweethearty.find(params[:id])
    @sweethearty.destroy

    respond_to do |format|
      format.html { redirect_to sweethearties_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sweethearties_helper.rb
module SweetheartiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CupidParty2</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :id_sender %><br />
    <%= f.number_field :id_sender %>
  </div>
  <div class="field">
    <%= f.label :id_receiver %><br />
    <%= f.number_field :id_receiver %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Id sender</th>
    <th>Id receiver</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.message %></td>
    <td><%= message.id_sender %></td>
    <td><%= message.id_receiver %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @message.message %>
</p>

<p>
  <b>Id sender:</b>
  <%= @message.id_sender %>
</p>

<p>
  <b>Id receiver:</b>
  <%= @message.id_receiver %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/rates/_form.html.erb
<%= form_for(@rate) do |f| %>
  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% @rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_rater %><br />
    <%= f.number_field :id_rater %>
  </div>
  <div class="field">
    <%= f.label :id_rated %><br />
    <%= f.number_field :id_rated %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<h1>Listing rates</h1>

<table>
  <tr>
    <th>Id rater</th>
    <th>Id rated</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rates.each do |rate| %>
  <tr>
    <td><%= rate.id_rater %></td>
    <td><%= rate.id_rated %></td>
    <td><%= rate.rating %></td>
    <td><%= link_to 'Show', rate %></td>
    <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
    <td><%= link_to 'Destroy', rate, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/new.html.erb
<h1>New rate</h1>

<%= render 'form' %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id rater:</b>
  <%= @rate.id_rater %>
</p>

<p>
  <b>Id rated:</b>
  <%= @rate.id_rated %>
</p>

<p>
  <b>Rating:</b>
  <%= @rate.rating %>
</p>


<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>

app/views/sweethearties/_form.html.erb
<%= form_for(@sweethearty) do |f| %>
  <% if @sweethearty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sweethearty.errors.count, "error") %> prohibited this sweethearty from being saved:</h2>

      <ul>
      <% @sweethearty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_sweetheater %><br />
    <%= f.number_field :id_sweetheater %>
  </div>
  <div class="field">
    <%= f.label :id_sweethearted %><br />
    <%= f.number_field :id_sweethearted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sweethearties/edit.html.erb
<h1>Editing sweethearty</h1>

<%= render 'form' %>

<%= link_to 'Show', @sweethearty %> |
<%= link_to 'Back', sweethearties_path %>

app/views/sweethearties/index.html.erb
<h1>Listing sweethearties</h1>

<table>
  <tr>
    <th>Id sweetheater</th>
    <th>Id sweethearted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sweethearties.each do |sweethearty| %>
  <tr>
    <td><%= sweethearty.id_sweetheater %></td>
    <td><%= sweethearty.id_sweethearted %></td>
    <td><%= link_to 'Show', sweethearty %></td>
    <td><%= link_to 'Edit', edit_sweethearty_path(sweethearty) %></td>
    <td><%= link_to 'Destroy', sweethearty, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sweethearty', new_sweethearty_path %>

app/views/sweethearties/new.html.erb
<h1>New sweethearty</h1>

<%= render 'form' %>

<%= link_to 'Back', sweethearties_path %>

app/views/sweethearties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id sweetheater:</b>
  <%= @sweethearty.id_sweetheater %>
</p>

<p>
  <b>Id sweethearted:</b>
  <%= @sweethearty.id_sweethearted %>
</p>


<%= link_to 'Edit', edit_sweethearty_path(@sweethearty) %> |
<%= link_to 'Back', sweethearties_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
    <th>Avatar</th>
    <th>Address</th>
    <th>Twitter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.description %></td>
    <td><%= user.avatar %></td>
    <td><%= user.address %></td>
    <td><%= user.twitter %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @user.id %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Description:</b>
  <%= @user.description %>
</p>

<p>
  <b>Avatar:</b>
  <%= @user.avatar %>
</p>

<p>
  <b>Address:</b>
  <%= @user.address %>
</p>

<p>
  <b>Twitter:</b>
  <%= @user.twitter %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>